# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 6 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
baseurl: https://Kazen-Renderer.github.io/
url: https://Kazen-Renderer.github.io
repository: kazen-renderer
permalink: /:year/:month/:title.html
authorurl: https://Kazen-Renderer.github.io
name: Kazen
author: 钟凌霄
